# Generated by Django 5.2.6 on 2025-10-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, default='media/no_image.png', null=True, upload_to='media'),
        ),
    ]
