# Generated by Django 5.2.6 on 2025-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, default='media/no_image.png', null=True, upload_to='blogs/'),
        ),
    ]
